
# Site settings
title: GO-INIT
description: |
  In IT 2 Win IT
owner: GO-INIT
first_published: 2022 
email: info@go-init.com
baseurl: ""

social:
  twitter: https://twitter.com/logitblog
  github: https://github.com/ryanbijkerk
  linkedin-square: https://linkedin.com/in/ryanbijkerk

# Build settings
markdown: kramdown
#sass:
#  style: compressed
